### PR TITLE
Added all the object textures to object ids and new raw objectIDs.json

### PR DESCRIPTION
**Pull request by iliasHDZ**
All of the object textures have been added to `assets/objectIDs/`. Also, a json file `objectsIDs.json` containing the table data but in json.

I know this is alot of files but i don't know how to do it differently. If you have a suggestion, please tell me.

### CODE REVIEW

**Comment by iliasHDZ** [comment]
Why has no one commented about this?

**Comment by Cvolton** [comment]
because

**Comment by FigmentBoy** [comment]
because

**Comment by iliasHDZ** [comment]
hmm, what should i do now?

**Comment by SMJSGaming** [comment]
This won't be added as this makes the repo extremely big for no good reason, anyone can just take apart a sheet and check it that way anyways.

**Comment by iliasHDZ** [comment]
ok, thanks for answering!

**Pull request closed without merging**
