### PR TITLE
adding kool lib

### PR DESCRIPTION
**Pull request by Cos8o**

### CODE REVIEW

**Comment by NeKitDS** [comment]
I think you need to put 2 empty lines around the item to adjust it to others.

**Comment by SMJSGaming** [comment]
not happening, this is a project for the gd programming server which you left

**Comment by Cvolton** [comment]
0/10 not hyperdash

**Comment by Homurasama** [comment]
this was closed for no reason out of bias lmao; this is not a project *for* gd programming, it's for anyone to use for creating their project or ideas with the knowledge of how gd works, meaning it's an open community project **BY** gd programming's experts, not FOR gd programming

**Comment by Cos8o** [comment]
how dare you

**Pull request closed without merging**
